spring:
  application:
    name: Herizon
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/herizon?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useSSL=false&readOnlyPropagatesToServer=false
    username: root
    password: 20050113

mybatis-flex:
  global-config:
    db-type: mysql
    logic-delete-column: deleted
    logic-delete-value: 1
    logic-normal-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.mybatisflex: debug
    org.example.herizon: debug

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.example.herizon.controller
  show-actuator: false
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# 微信小程序配置
wechat:
  miniprogram:
    # 小程序appid（从manifest.json获取）
    app-id: wxdfc093b40156d130
    # 小程序secret（需要在微信公众平台获取）
    # 开发环境临时配置 - 生产环境请使用环境变量
    app-secret: 1a3bbd5a751a8511dd6e77b481b607a3
    # 微信API地址
    code2session-url: https://api.weixin.qq.com/sns/jscode2session



