spring:
  application:
    name: Herizon
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-524ybu4e.sql.tencentcdb.com:20852/herizon?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useSSL=false&readOnlyPropagatesToServer=false
    username: root
    password: Herizon123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-test-query: SELECT 1
      # 修复tx_read_only系统变量兼容性问题
      read-only: false
      # 禁用连接池的只读检查，避免在旧版MySQL上出现兼容性问题
      data-source-properties:
        useInformationSchema: true
        nullCatalogMeansCurrent: true
        # 兼容旧版MySQL，禁用某些功能检查
        useServerPrepStmts: false
        cachePrepStmts: false
      # 关键配置：禁用isReadOnly检查，解决tx_read_only错误
      connection-init-sql: SELECT 1
      is-read-only: false

app:
  public-base-url: ${PUBLIC_BASE_URL:https://herizon-188137-4-1379688731.sh.run.tcloudbase.com/api}

mybatis-flex:
  global-config:
    db-type: mysql
    logic-delete-column: deleted
    logic-delete-value: 1
    logic-normal-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.mybatisflex: debug
    org.example.herizon: debug

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.example.herizon.controller
  show-actuator: false
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# 微信小程序配置
wechat:
  miniprogram:
    # 小程序appid（从manifest.json获取）
    app-id: wxdfc093b40156d130
    # 小程序secret（需要在微信公众平台获取）
    # 开发环境临时配置 - 生产环境请使用环境变量
    app-secret: 1a3bbd5a751a8511dd6e77b481b607a3
    # 微信API地址
    code2session-url: https://api.weixin.qq.com/sns/jscode2session


